name: Deploy to Laravel Vapor

on:
  push:
    branches:
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3.9'  
        extensions: mbstring, bcmath, xml, curl, gd

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

    - name: Install Vapor CLI
      run: composer global require laravel/vapor-cli

    - name: Deploy to Vapor
      env:
        VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        VAPOR_TEAM_ID: 63169
        VAPOR_ENVIRONMENT: 'production'
      run: |
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        vapor deploy $VAPOR_ENVIRONMENT
